services:
  # 1. El Emulador de AWS (Floci) para Persistencia y Estructura (Cognito, DynamoDB, ElastiCache)
  aws-emulator:
    image: floci/floci:latest
    container_name: acity_aws_emulator
    ports:
      - "4566:4566"  # Puerto unificado AWS local
    environment:
      - SERVICES=dynamodb,cognito,elasticache
      - DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
    volumes:
      - floci_data:/root/.floci

  # 2. Capa de Simulación de API Gateway NATIVA (Cero dependencias externas, Ultra estable)
  infra-auth-mock:
    image: node:20-alpine
    container_name: infra_auth_mock
    ports:
      - "5001:5001"
    volumes:
      - ./mock:/app/mock
    working_dir: /app
    environment:
      - PORT=5001
      - WS_TOKEN_EXPIRES_IN=3600
    command: node mock/server.js
    depends_on:
      - aws-emulator

volumes:
  floci_data: