locals {

  sufix = "${var.tags.vertical_business}-${var.tags.project}"

  lambdas_files = {
    "define_auth_challenge"       = "cognito/define-auth-challenge.py"
    "create_auth_challenge"       = "cognito/create-auth-challenge.py"
    "refresh_token"               = "calimaco/refresh-token.mjs"
    "claim_code_promotion"        = "calimaco/claim-code-promotion.mjs"
    "get_user_accounts"           = "calimaco/get-user-accounts.mjs"
    "cancel_user_promotion"       = "calimaco/cancel-user-promotion.mjs"
    "get_user_active_promotions"  = "calimaco/get-user-active-promotions.mjs"
    "get_user_pending_promotions" = "calimaco/get-user-pending-promotions.mjs"
    "get_user_files"              = "calimaco/get-user-files.mjs"
    "auto_exclude"                = "calimaco/auto-exclude.mjs"
    "get_auto_exclutions"         = "calimaco/get-auto-exclutions.mjs"
    "get_user_deposit_limits"     = "calimaco/get-user-deposit-limits.mjs"
    "user_payment_accounts"       = "calimaco/user-payment-accounts.mjs"
    "validate_session"            = "calimaco/validate-session.mjs"
    "get_users_per_preferences"   = "calimaco/get-users-per-preferences.mjs"
    "get_user_per_preferences"    = "calimaco/get-user-per-preferences.mjs"
    "active_user_promotion"       = "calimaco/active-user-promotion.mjs"
    "get_transactions_history"    = "calimaco/get-transactions-history.mjs"
    "get_operations_history"      = "calimaco/get-operations-history.mjs"
    "save_user_consent"           = "calimaco/save-user-consent.mjs"
    "get_web_fragment"            = "calimaco/get-web-fragment.mjs"
    "get_banners"                 = "calimaco/get-banners.mjs"
    "get_selectables_promotions"  = "calimaco/get-selectables-promotions.mjs"
    "get_countries"               = "calimaco/get-countries.mjs"
    "get_machine_by_name"         = "calimaco/get-machine-by-name.mjs"
    "get_providers"               = "calimaco/get-providers.mjs"
    "get_deposit_lobby"           = "calimaco/get-deposit-lobby.mjs"
    "get_states"                  = "calimaco/get-states.mjs"
    "get_provinces"               = "calimaco/get-provinces.mjs"
    "get_cities"                  = "calimaco/get-cities.mjs"
    "get_payout_lobby"            = "calimaco/get-payout-lobby.mjs"
    "validate_code_otp"           = "calimaco/validate-code-otp.mjs"
    "generate_code_otp"           = "calimaco/generate-code-otp.mjs"
    "national_id_available"       = "calimaco/national-id-available.mjs"
    "email_available"             = "calimaco/email-available.mjs"
    "mobile_available"            = "calimaco/mobile-available.mjs"
    "alias_available"             = "calimaco/alias-available.mjs"
    "save_user_deposit_limits"    = "calimaco/save-user-deposit-limits.mjs"
    "save_personal_preferences"   = "calimaco/save-personal-preferences.mjs"
    "active_user_promotion"       = "calimaco/active-user-promotion.mjs"
    "save_user_detail"            = "calimaco/save-user-details.mjs"
    "add_user_payment_account"    = "calimaco/add-user-payment-account.mjs"
    "pending_payouts"             = "calimaco/get-pending-payouts.mjs"
    "cancel_payout"               = "calimaco/cancel-payout.mjs"
    "deposit"                     = "calimaco/deposit.mjs"
    "payout"                      = "calimaco/payout.mjs"
    "get_provider_info"           = "calimaco/get-provider-info.mjs"
    "get_user_detail"             = "calimaco/get-user-detail.mjs"
    "update_password"             = "calimaco/update-password.mjs"
    "forgot_password"             = "calimaco/forgot-password.mjs"
    "log_out"                     = "calimaco/log-out.mjs"
    "sign-in"                     = "utils/sign-in.mjs"
    "upload_file"                 = "calimaco/upload-file.mjs"
    "get_deposit_info"            = "calimaco/get-deposit-info.mjs"
    "delete_user_payment_account" = "calimaco/delete-user-payment-account.mjs"
    "renew-refresh-session"       = "calimaco/renew-refresh-session.mjs"
    "refresh-session-revoke"      = "calimaco/refresh-session-revoke.mjs"
    "refresh-session-obtain"      = "calimaco/refresh-session-obtain.mjs"
    "ws_guest_session"            = "websocket/guest-session.mjs"
    "ws_session"                  = "websocket/session.mjs"
    "ws_connect"                  = "websocket/connect.mjs"
    "ws_disconnect"               = "websocket/disconnect.mjs"
  }

  lambdas_folder = {
    "verify_auth_challenge" = "cognito/verify-auth-challenge"
    "pre_token_generation"  = "cognito/pre-token-generation"
    "crypto"                = "utils/crypto"
  }

  lambda_config = {
    memory_size   = 1024
    timeout       = 30
    architectures = ["arm64"]
  }

  lambdas_files_name = [
    "define-auth-challenge",       # 0
    "create-auth-challenge",       # 1
    "verify-auth-challenge",       # 2
    "pre-token-generation",        # 3
    "get-user-detail",             # 4
    "sign-in",                     # 5
    "crypto",                      # 6
    "update-password",             # 7
    "forgot-password",             # 8
    "log-out",                     # 9
    "refresh-token",               # 10
    "claim-code-promotion",        # 11
    "get-user-accounts",           # 12
    "cancel-user-promotion",       # 13
    "get-user-active-promotions",  # 14
    "get-user-pending-promotions", # 15
    "get-user-files",              # 16
    "auto-exclude",                # 17
    "get-auto-exclutions",         # 18
    "get-user-deposit-limits",     # 19
    "user-payment-accounts",       # 20
    "validate-session",            # 21
    "get-users-per-preferences",   # 22
    "get-user-per-preferences",    # 23
    "active-user-promotion",       # 24
    "get-transactions-history",    # 25
    "get-operations-history",      # 26
    "save-user-consent",           # 27
    "get-web-fragment",            # 28
    "get-banners",                 # 29
    "get-selectables-promotions",  # 30
    "get-countries",               # 31
    "get-machine-by-name",         # 32
    "get-providers",               # 33
    "get-deposit-lobby",           # 34
    "get-states",                  # 35
    "get-provinces",               # 36
    "get-cities",                  # 37
    "get-payout-lobby",            # 38
    "validate-code-otp",           # 39
    "generate-code-otp",           # 40
    "national-id-available",       # 41
    "email-available",             # 42
    "mobile-available",            # 43
    "alias-available",             # 44
    "save-user-deposit-limits",    # 45
    "save-personal-preferences",   # 46
    "save-user-details",           # 47
    "add-user-payment-account",    # 48
    "get-pending-payouts",         # 49
    "cancel-payout",               # 50
    "deposit",                     # 51
    "payout",                      # 52
    "get-provider-info",           # 53
    "upload-file",                 # 54
    "get-deposit-info",            # 55
    "delete-user-payment-account", # 56
    "renew-refresh-session",       # 57
    "refresh-session-revoke",      # 58
    "refresh-session-obtain",      # 59
    "guest-session",               # 60
    "session",                     # 61
    "connect",                     # 62
    "disconnect",                  # 63
  ]

}
